// Tiny labelled set for /check. GROW THIS TO 40 (20 scam / 20 genuine) from your own inbox before 3 PM
// and publish the real numbers. Genuine messages matter most: a checker that flags every bank OTP is useless.
export const SCAM = [
  "Dear Consumer, your electricity power will be disconnected tonight at 9.30 pm because your previous month bill was not updated. Please immediately contact our electricity officer 8240471159. Thank you.",
  "Dear customer your SBI account will be blocked today. Update your KYC immediately: http://sbi-kyc-update.top/login",
  "Sir I have sent the payment. Scan this QR and enter your UPI PIN to receive Rs 4500 in your account. Army payment system.",
  "This is Mumbai Customs. A parcel with your Aadhaar containing MDMA is seized. You are under digital arrest. Do not tell anyone and stay on camera.",
  "Congratulations! You have won KBC lottery of Rs 25,00,000. WhatsApp 9876543210 immediately to claim prize.",
  "Your refund of Rs 2,999 is pending. Install QuickSupport app and share the OTP with our executive to get the refund.",
  "प्रिय उपभोक्ता, आपकी बिजली आज रात 9:30 बजे काट दी जाएगी। तुरंत संपर्क करें 8240471159",
  "For account verification please transfer a refundable security deposit to the RBI secure account. Do not inform anyone.",
  "send me $400 on the provided no",
  "Hi mum, this is my new number, my phone is broken. Please send Rs 20,000 to this number urgently, I will explain later.",
  "bhai urgent hai 5000 rupaye bhej do is number pe, kal wapas kar dunga",
  "Please transfer ₹15,000 to this UPI id today itself: helpdesk.refund@okbank",
  "आपका बैंक खाता आज बंद हो जाएगा। KYC अपडेट करने के लिए तुरंत इस लिंक पर क्लिक करें: http://sbi-kyc.top/verify",
  "बधाई हो! आपने KBC लॉटरी में 25 लाख रुपये जीते हैं। इनाम पाने के लिए 9876543210 पर WhatsApp करें।",
  "मम्मी मेरा फ़ोन खराब हो गया है, यह मेरा नया नंबर है। जल्दी से 5000 रुपये भेज दो।",
  "सर आपका पार्सल कस्टम में पकड़ा गया है। आप डिजिटल अरेस्ट में हैं, किसी को मत बताना।",
  "Part time work from home. Earn 3000 per day. Join our Telegram task group, like and subscribe videos and get paid.",
  "घर बैठे कमाएँ! रोज़ 2000 रुपये कमाने का मौका। अभी WhatsApp करें।",
];
export const GENUINE = [
  "482913 is your OTP for txn of INR 1,250.00 at AMAZON. Do not share it with anyone. -HDFC Bank",
  "Rs.500.00 debited from A/c XX1234 on 20-09-26 to VPA merchant@okaxis (UPI Ref 426512345678). Not you? Call 18002586161 -SBI",
  "Your order has been shipped and will be delivered by tomorrow. Track at https://www.amazon.in/track",
  "Hi beta, reached home safely. Call me when you are free.",
  "Your electricity bill of Rs 1,840 for Aug is generated. Due date 28-09-2026. Pay via the official app or website.",
  "OTP for login is 771204. Valid for 10 minutes. Never share your OTP with anyone, even bank staff.",
  "Reminder: Your appointment with Dr. Mehta is scheduled for 22 Sep at 5:30 PM.",
  "आपका OTP 552310 है। इसे किसी को न बताएं। - आपका बैंक",
  "Your SIP of Rs 2,000 has been processed successfully. Units will be allotted in 2 working days.",
  "Salary of INR 45,000.00 credited to your A/c XX9921 on 20-09-26. Avl bal INR 61,204.55 -ICICI Bank",
  "Lunch at 1? I will pay today, you paid last time.",
  "Your Amazon order of Rs 1,299 is out for delivery. Pay on delivery or pay online in the app.",
  "आपके खाते XX1234 में 20-09-26 को ₹5,000 जमा किए गए। उपलब्ध शेष ₹12,450। - SBI",
  "आपका बिजली बिल ₹1,840 जनरेट हो गया है। अंतिम तिथि 28-09-2026। आधिकारिक ऐप से भुगतान करें।",
  "बेटा घर पहुँच कर फ़ोन करना। खाना फ्रिज में रखा है।",
  "आपकी गैस बुकिंग हो गई है। सिलेंडर 2 दिन में पहुँच जाएगा। बुकिंग नंबर 448211।",
  "Your interview for the part-time content writer role is scheduled on Monday at 11 AM at our Mohali office.",
  "Reminder: work from home is allowed on Friday. Please update the team tracker.",
];
